### ISSUE TITLE
pantheon.yml calls quicksilver-pushback but it is not installed.

### ISSUE THREAD

**Issue by thejimbirch** [kanopi/drupal-starter#230]
Is this needed? If so, we need to add it.  If not, we need to remove it from the pantheon.yml

```
  sync_code:
    after:
      - type: webphp
        description: Push changes back to GitHub if needed
        script: private/scripts/quicksilver/quicksilver-pushback/push-back.php
```
